### ISSUE TITLE
📦 Feature - Move "Add Chat Window" Button (Duplicate)

### ISSUE THREAD

**Issue by Ryguy6001** [Valour-Software/Valour#76] opened 2021-02-01 13:52 UTC
On phone the add a chat window is in the top left corner and it would be nice to move it to top right. I do know that phone is not fully ready but when you are making the set up for it please include this.
![40C9CE11-8890-40D2-80EE-AF6B426782CB](https://user-images.githubusercontent.com/72236069/106467413-342eff80-6462-11eb-90fd-5580d198f647.jpeg)

**Comment by brndnln** [comment] 2021-02-01 14:26
This is a duplicate of an issue I already opened at #67

**Closed by brndnln** 2021-02-01 14:26 UTC
Labels: Duplicate
